const topCars = [
    {
      title: "Toyota Corolla",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Honda Civic",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ford Mustang",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chevrolet Camaro",
      year: 2019,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Tesla Model 3",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "BMW 3 Series",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Audi A4",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mercedes-Benz C-Class",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Volkswagen Golf",
      year: 2019,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Porsche 911",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Subaru Outback",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Hyundai Elantra",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Kia Soul",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mazda CX-5",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Nissan Altima",
      year: 2019,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Jeep Wrangler",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Dodge Charger",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Lexus RX",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ferrari 488 GTB",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Lamborghini Huracan",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Volvo XC90",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Land Rover Range Rover",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Jaguar F-Type",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mini Cooper",
      year: 2019,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chrysler 300",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Acura TLX",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Infiniti Q50",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Cadillac Escalade",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mitsubishi Outlander",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Peugeot 208",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Toyota Supra",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chevrolet Corvette",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ford Explorer",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Tesla Model S",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Audi Q7",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "BMW X5",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Honda Accord",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Hyundai Tucson",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Nissan GT-R",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mazda MX-5 Miata",
      year: 2019,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Jeep Grand Cherokee",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Kia Telluride",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Toyota Highlander",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ford F-150",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chevrolet Silverado",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "GMC Sierra",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Volvo XC60",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Land Rover Defender",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Porsche Macan",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "BMW i8",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Jaguar XE",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mercedes-Benz E-Class",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Audi R8",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Lexus IS",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Dodge Challenger",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ferrari SF90 Stradale",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Lamborghini Aventador",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Toyota Prius",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Subaru Impreza",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Honda CR-V",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mitsubishi Eclipse Cross",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Peugeot 3008",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Renault Clio",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Fiat 500",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Citroën C3",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Volkswagen Passat",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chevrolet Tahoe",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ford Edge",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mazda6",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Hyundai Kona",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Kia Stinger",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Nissan Pathfinder",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Subaru Forester",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mercedes-Benz GLE",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Audi A6",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "BMW 5 Series",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Tesla Model Y",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Toyota RAV4",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Chevrolet Equinox",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Honda HR-V",
      year: 2020,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Jeep Cherokee",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Ford Escape",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Mazda CX-9",
      year: 2021,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Volvo V60",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Land Rover Discovery",
      year: 2023,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
    {
      title: "Porsche Taycan",
      year: 2022,
      type: "coupe",
      users: 4,
      manual: "manual",
      price: "$400/d",
    },
  ];

  
export default topCars